### ISSUE TITLE
esm error: Uncaught TypeError: Cannot set properties of undefined (setting 'Stream')

### ISSUE THREAD

**Issue by yezige** [amrbashir/meilisearch-docsearch#149]
Use:
```html
<script type="module" async>
  import { docsearch } from "https://cdn.jsdelivr.net/npm/meilisearch-docsearch@0.6.0/+esm"
  docsearch({
    container: "#docsearch",
    host: "YOUR_HOST_URL",
    apiKey: "YOUR_SEARCH_API_KEY",
    indexUid: "YOUR_INDEX_UID",
  })
</script>
```
This File`https://cdn.jsdelivr.net/npm/meilisearch@0.35.0/+esm` reported an error
![image](https://github.com/user-attachments/assets/a45b9fd0-5b82-4e98-9c53-1a0b6a1d634e)

Any useful tips are greatly appreciated.

**Comment by amrbashir** [comment]
Try using https://cdn.jsdelivr.net/npm/meilisearch-docsearch@0.6.0/dist/index.min.js


If that doesn't work, please checkout the "Usage through CDN" section in README.md https://github.com/tauri-apps/meilisearch-docsearch#usage-through-cdn

**Comment by yezige** [comment]
> Try using https://cdn.jsdelivr.net/npm/meilisearch-docsearch@0.6.0/dist/index.min.js
> 
This doesn't work either,reported an error.
```
Uncaught TypeError: Failed to resolve module specifier "solid-js/web". Relative references must start with either "/", "./", or "../".
```

> If that doesn't work, please checkout the "Usage through CDN" section in README.md https://github.com/tauri-apps/meilisearch-docsearch#usage-through-cdn

This method will block the script, pollute the window environment, and cannot use async `<script type="module" async>`

Any useful tips are greatly appreciated.

**Comment by amrbashir** [comment]
> This method will block the script, pollute the window environment, and cannot use async `<script type="module" async>`

This case should normally be covered by an ESM file and although [cdn.jsdelivr.net/npm/meilisearch-docsearch@0.6.0/dist/index.min.js](https://cdn.jsdelivr.net/npm/meilisearch-docsearch@0.6.0/dist/index.min.js) is ESM, it relies on being installed as an NPM package so `solid-js` and `meilisearch` dependencies are resolved from `node_modules`


I believe we can build a `index.bundled.esm.min.js` and publish it as well. It is similar to how the global `index.global.js` script is bundled https://github.com/tauri-apps/meilisearch-docsearch/blob/e6469b6fe992d8aa2065b698fb96c52345637143/tsup.config.ts#L22-L36

I don't think I have the time to resolve this issue atm, would you like to work on this?

**Comment by yezige** [comment]
Haha, I'm not a front-end developer, but you gave me a new idea.

**Comment by amrbashir** [comment]
No worries, I will keep this on my todo list, hopefully I can find sometime for it soon

**Comment by yezige** [comment]
Just add this
```
 {
    entry: ["src/index.tsx"],
    format: ["iife"],
    clean: !config.watch,
    minify: false,
    esbuildPlugins: [solidPlugin()],
    outExtension: () => ({
      js: ".bundled.esm.js",
    }),
    env: {
      VERSION,
    },
    globalName: "__docsearch_meilisearch__",
    platform: "browser",
    footer: {
      js: "export{__docsearch_meilisearch__ as default}",
    },
  },
```
and use like this
```
<script type="module" async>
  import meilisearchDocsearch from "/js/index.bundled.esm.js"
  meilisearchDocsearch.docsearch({
    container: "#docsearch",
    host: "YOUR_HOST_URL",
    apiKey: "YOUR_SEARCH_API_KEY",
    indexUid: "YOUR_INDEX_UID",
  })
</script>
```

**Comment by amrbashir** [comment]
@yezige thank you, I have modified your code a bit and add it in https://github.com/tauri-apps/meilisearch-docsearch/commit/a20acbc1987c34a981652e572dd994fd905a1df2 and updated [Usage through CDN](https://github.com/tauri-apps/meilisearch-docsearch#usage-through-cdn) section

**Comment by yezige** [comment]
Cool, just add this attribute like you did: `noExternal : [/(.*)/]`, it's ready to run.
