### ISSUE TITLE
When typing quickly, can ignore the previous useless request?

### ISSUE THREAD

**Issue by yezige** [amrbashir/meilisearch-docsearch#153]
When typing quickly, can ignore the previous useless request?

eg. I search for`hains`, and will search for `ha`,`hai`, and`hains` respectively.

**Comment by yezige** [comment]
I have an idea that I don't know if it can be realized, as follows:
```js
var timeout
function oninput(s) {
  timeout && clearTimeout(timeout)
  timeout = setTimeout(() => {
    doquery(s)
  }, 500)
}
function doquery(s) {
  console.log(s)
}
oninput('ha')
oninput('hai')
oninput('hains')

setTimeout(() => {
  oninput('hains point')
}, 1000)
```
output:
```
hains
hains point
```

It can be seen that when typing quickly, only the real requirements:`hains`, `hains point` are successfully executed

**Comment by amrbashir** [comment]
We do debounce search queries, see https://github.com/tauri-apps/meilisearch-docsearch/blob/97cb6a2d03706a7e7432344d6ecd1a3694f0b203/src/DocSearchModal.tsx#L203-L227

it is 100ms though, not 500ms

**Comment by yezige** [comment]
Cool, maybe 100ms is too short.

**Comment by amrbashir** [comment]
I will probably make this configurable instead.

**Comment by yezige** [comment]
Great, but I think 100ms is indeed too low, 500ms will be better, it seems that there is no need to change it to configurable, because everyone's needs are not much different.

**Comment by amrbashir** [comment]
from my previous testing, 500ms was a bit slow and noticeable specially when selecting some text on page then hitting the search hotkey.

**Comment by yezige** [comment]
Hmm, you need to decide the specific data. this time should be greater than the speed of normal people typing two letters.

**Comment by yezige** [comment]
加油老哥

**Comment by yezige** [comment]
太秀了，神速
